CREATE TABLE IF NOT EXISTS users (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '用户 ID，主键',
  username VARCHAR(50) NOT NULL UNIQUE COMMENT '用户名，唯一',
  email VARCHAR(100) DEFAULT NULL COMMENT '邮箱，可选',
  password VARCHAR(255) NOT NULL COMMENT '加密后的密码',
  avatar VARCHAR(255) DEFAULT NULL COMMENT '用户头像地址',
  status TINYINT NOT NULL DEFAULT 1 COMMENT '状态（0禁用，1启用）',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户表';
